default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: localhost

development:
  <<: *default
  database: share_me

test:
  <<: *default
  database: share_me_test

production:
  <<: *default
  database: share_me_prod