# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d5db4b7449090368f5f219662937203174339a11754968369d8a949cd0062d74354c8a616450eaa97f647ce66cadcd33a2f89a364a8b8c73643d220bb640876

test:
  secret_key_base: 6eeb9adee92c0794a5caa7ea4dd885002e11acdb669d19c7f646bff193251aaad1fd965c4ffd0d0126c0453d9235ae602c4543a4d3ffcadca7089a7214559032

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
